#!/bin/bash

# This script skips the built library archive files and runs a Hello World
# test directly. This is good for a quick smoke test.

# This should be run from the root project directory.

#Using separate compilation for now, because it's easier to get GCC to link things in the correct order than it is DMD

dmd -c \
    -I../dstruct/source \
    -I../dsmoke/source \
    -Isource \
    -debug -d -inline \
    examples/hello_world.d

gcc \
    hello_world.o \
    -o examples/hello_world \
    -m64 \
    -Xlinker lib/libdqt.a \
    -Xlinker ../dsmoke/lib/libdsmoke.a \
    -L/usr/lib64/qt4 \
    -lstdc++ \
    -lQtCore \
    -lsmokeqtcore \
    -lsmokeqtgui \
    -L/opt/dmd-2.065/lib64 \
    -Xlinker -rpath \
    -Xlinker /opt/dmd-2.065/lib64 \
    -Xlinker --export-dynamic \
    -l:libphobos2.a \
    -lpthread -lm -lrt

examples/hello_world
rm hello_world.o
